require 'rake'
require 'rake/rdoctask'
require 'spec/rake/spectask'

Spec::Rake::SpecTask.new('spec') do |t|
  t.libs << 'lib'
  t.libs << 'spec'
  t.spec_opts << "--color"
  t.warning = true
  t.verbose = true
  t.rcov = true
  t.rcov_opts += ["-x /Library", "-x spec"]
end

Rake::RDocTask.new do |rdoc|
  rdoc.rdoc_dir = 'html'
  rdoc.template = 'hefss'
  rdoc.options << '--line-numbers'
  # rdoc.rdoc_files.add('README')
  rdoc.rdoc_files.add('lib/**/*.rb')
end

task :default => [:spec]
